# This Script only accepts Product URL's that look like this. I hope you see the difference between page examples.

# Example 1 - Nvidia RTX 3080:
# https://www.bestbuy.com/site/nvidia-geforce-rtx-3080-10gb-gddr6x-pci-express-4-0-graphics-card-titanium-and-black/6429440.p?skuId=6429440
# Example 2 - PS5:
# https://www.bestbuy.com/site/sony-playstation-5-console/6426149.p?skuId=6426149
# Example 3 - Ryzen 5600x:
# https://www.bestbuy.com/site/amd-ryzen-5-5600x-4th-gen-6-core-12-threads-unlocked-desktop-processor-with-wraith-stealth-cooler/6438943.p?skuId=6438943

# This Script does not accept Product URL's that look like this.
# https://www.bestbuy.com/site/searchpage.jsp?st=rtx+3080&_dyncharset=UTF-8&_dynSessConf=&id=pcat17071&type=page&sc=Global&cp=1&nrp=&sp=&qp=&list=n&af=true&iht=y&usc=All+Categories&ks=960&keys=keys

# Highly Recommend To set up Twilio Account to receive text messages. So if bot doesn't work you'll at least get a phone
# text message with the url link. You can click the link and try manually purchasing on your phone.

# Twilio is free. Get it Here.
# www.twilio.com/referral/BgLBXx


# -----------------------------------------------Steps To Complete------------------------------------------------------

# Test Link 1 - Ryzen 5800x seems to be available quite often. It is the best URL to try out preorder script.
# To actually avoid buying CPU, you can comment out Line 220. Uncomment the line when you are done testing.
# https://www.bestbuy.com/site/amd-ryzen-7-5800x-4th-gen-8-core-16-threads-unlocked-desktop-processor-without-cooler/6439000.p?skuId=6439000

# Test Link 2 (cheap HDMI cable) - https://www.bestbuy.com/site/dynex-6-hdmi-cable-black/6405508.p?skuId=6405508
# *Warning* - Script will try to checkout the HDMI cable twice since this is how the Bestbuy preorder script works
# Best buy makes us click the add to cart button twice to enter Queue System.
# Don't worry about script buying two graphics cards though. The script will only buy one.
# As well, Best buy won't let you check out more than 1 item.
# To actually avoid buying HDMI cable, set test_mode to 'True'. Set to 'False' when you are done testing.

# 1. General Settings
test_mode: True  # Set test_mode to True when testing bot checkout process, and set it to False when your done testing.
headless_mode: False  # Set False for testing. If True, it will hide Firefox in background for faster checkout speed.
docker_mode: False # Set False to run in Pycharm. If True, will only run in Docker.
webpage_refresh_timer: 3  # Default 3 seconds. If slow internet and the page isn't fully loading, increase this.

# 2. Product url: '#' comments out the product and the script will not attempt to purchase those commented products.
product: https://www.bestbuy.com/site/nvidia-geforce-rtx-3080-10gb-gddr6x-pci-express-4-0-graphics-card-titanium-and-black/6429440.p?skuId=6429440
#product: https://www.bestbuy.com/site/amd-ryzen-7-5800x-4th-gen-8-core-16-threads-unlocked-desktop-processor-without-cooler/6439000.p?skuId=6439000
#product: https://www.bestbuy.com/site/dynex-6-hdmi-cable-black/6405508.p?skuId=6405508
# 3. Firefox Profile
firefox_profile: C:\Users\Trebor\AppData\Roaming\Mozilla\Firefox\Profiles\t6inpqro.Robert-1613116705360
# 4. Credit Card CVV Number
cvv: 123
# 5. Twilio Account
twilio:
  toNumber: your_phonenumber
  fromNumber: twilio_phonenumber
  accountSid: ssid
  authToken: authtoken
